import {Platform, StatusBar, StyleSheet} from 'react-native';
import {withSafeAreaInsets} from 'react-native-safe-area-context';

export default StyleSheet.create({
  Container: {
    flex: 1,
    backgroundColor: '#ffff',
    paddingLeft: 20,
    paddingRight: 20,
    // paddingTop: Platform.OS = "android" ? StatusBar.currentHeight : 0,
    // alignItems: 'center'
  },
  mainView: {
    width: '75%',
    backgroundColor: 'white',
    marginTop: 20,
    paddingRight: 20,
    paddingLeft: 5,
  },
  subView: {
    width: '30%',
    backgroundColor: '#F5F5F5',
  },
  sideViewWrapper: {
    marginTop: 20,
    // paddingLeft: 45,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center'
  },
  rowDirection: {
    flexDirection: 'row',
  },
  flexEnd: {
    justifyContent: 'space-between',
  },
  Title: {
    fontSize: 24,
    fontWeight: 'bold',
    lineHeight: 29,
    textAlign: 'center',
  },
  notifStyle: {
    marginTop: 8,
  },
  subTitle: {
    marginTop: 20,
  },
  greetingText: {
    fontWeight: '400',
    fontStyle: 'normal',
    fontSize: 12,
    lineHeight: 15,
  },
  nameStyle: {
    fontSize: 36,
    fontWeight: 'bold',
    fontStyle: 'normal',
    lineHeight: 44,
  },
  kitchenStyle: {
    marginTop: 30,
    marginBottom: 20,
    // backgroundColor: 'green',
  },
  greyStyle: {
    position: 'absolute',
    zIndex: 500,
  },
  activeWrapper: {
    position: 'absolute',
    top: 260,
    zIndex: 600,
    left: 20,
    flexDirection: 'row',
  },
  activeText: {
    fontWeight: 'bold',
    fontSize: 18,
    lineHeight: 22,
    color: '#FFFFFF',
    marginLeft: 7,
  },
  tempStyle: {
    backgroundColor: '#FB7B05',
    width: 110,
    height: 110,
    padding: 15,
    borderRadius: 18,
    marginRight: 23,
  },
  tempStyle2: {
    backgroundColor: '#E7E7E7',
    width: 110,
    height: 110,
    padding: 15,
    borderRadius: 18,
    marginRight: 23,
  },
  iconStyle: {
    alignSelf: 'flex-end',
  },
  ActiveTextColor: {
    color: 'white',
    fontSize: 36,
    lineHeight: 41,
  },
  ActiveDefaultTextColor: {
    color: 'black',
    fontSize: 36,
    lineHeight: 41,
  },
  ActiveSubTextColor: {
    color: 'white',
    fontSize: 23,
    lineHeight: 41,
    marginTop: 4,
  },
  ActiveDefaultSubTextColor: {
    color: 'black',
    fontSize: 23,
    lineHeight: 41,
    marginTop: 4,
  },
  ActiveSubTextColor2: {
    color: 'white',
    fontSize: 12,
    lineHeight: 41,
    marginTop: -4,
    marginLeft: 4,
  },
  buttomTabText: {
    color: 'white',
    fontSize: 14,
    fontWeight: 'bold',
    lineHeight: 17,
  },
  defaultbuttomTabText: {
    color: 'black',
    fontSize: 14,
    fontWeight: 'bold',
    lineHeight: 17,
  },
  defaultTop: {
    marginTop: 20,
  },
  SideIconTabWrapper: {
    // marginLeft: 30,
    marginTop: 70,
    height: 50,
    display: 'flex',
    // borderWidth: 1
  },
  sideIcon: {
    height: 60,
    width: 60,
    backgroundColor: '#E7E7E7',
    marginBottom: 30,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 15,
  },
  activeStyleIcon: {
    height: 60,
    width: 60,
    backgroundColor: '#FB7B05',
    marginBottom: 30,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 15,
  },
  sideIcon2: {
    height: 60,
    width: 60,
    backgroundColor: '#FB7B05',
    marginBottom: 30,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 15,
  },
  buttomButton: {
    height: 60,
    width: 60,
    backgroundColor: '#12B293',
    // marginBottom: 100,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 15,
    // position: 'absolute',
    // top: 100,
    // marginTop: 450,
    alignSelf: 'center',
    margin: 30
  },
  userDevices: {
    // borderWidth: 1,
    height: '85%',
    width: '100%',
    paddingTop: 50,
  },
  room: {
    // borderWidth: 1,
    width: '100%',
    height: 60,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-start',
  },
  roomState: {
    // borderWidth: 1,
    // width: '20%',
    // height: '100%',
    // paddingTop: 8,
  },
  roomType: {
    // borderWidth: 1,
    width: '50%',
    height: '100%',
    paddingLeft: 15,
  },
  roomSwitch: {
    width: '40%',
    height: '100%',
    // borderWidth: 1,
    display: 'flex',
    alignItems: 'flex-end',
    justifyContent: 'center',
    // paddingTop: 8,
  },
  roomTypeName: {
    fontSize: 18,
    fontWeight: 'bold',
    marginTop: 0,
    paddingTop: 0,
    color: '#575757',
  },
  connectedDevices: {
    // borderWidth: 1,
    width: '100%',
    paddingTop: 50,
  },
  devicesList: {
    // borderWidth: 1,
    height: 470,
  },
  connectedDevice: {
    width: '100%',
    // height: 100,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderBottomColor: '#E5E5E5',
    paddingTop: 21,
    borderBottomWidth: 2,
    borderColor: '#E5E5E5',
    paddingBottom: 14,
  },
});
